### ISSUE TITLE
有没有打算用pytorch实现一遍？

### ISSUE THREAD

**Issue by RichardHWD** [ShannonAI/CorefQA#4]
你们的MRC用于NER是用pytorch，Coref有没有考虑用pytorch写一遍，TF太恶心了 ...

**Comment by RichardHWD** [comment]
另外，numpy还没有1.17.0啊 ...

**Comment by vgtomahawk** [comment]
Facing a similar issue. A module named "independent" appears to be missing

```
Traceback (most recent call last):
  File "prepare_training_data.py", line 13, in <module>
    import util
  File "util.py", line 16, in <module>
    import independent
ModuleNotFoundError: No module named 'independen
```t'

**Comment by pku-wuwei** [comment]
那个脚本有点小问题，马上改一下。pytorch的话如果有需求我过年几天可以看着写一个。

**Comment by lu161513** [comment]
很棒的工作，的确TF太恶心了，还是pytorch舒服
