### ISSUE TITLE
ModuleNotFoundError: No module named independent

### ISSUE THREAD

**Issue by vgtomahawk** [ShannonAI/CorefQA#5]
On running python prepare_training_data.py , the following error is received [seems like a module named independent is absent?]

```
Traceback (most recent call last):
  File "prepare_training_data.py", line 13, in <module>
    import util
  File "util.py", line 16, in <module>
    import independent
ModuleNotFoundError: No module named 'independent'
```

**Comment by pku-wuwei** [comment]
Sorry for the inconvenience. We will fix the bug very soon.

**Comment by vgtomahawk** [comment]
Thanks!!

**Comment by pku-wuwei** [comment]
Hi, the bug is fixed, contact me if you have any problem.

**Comment by vgtomahawk** [comment]
Thanks!! 

I don't get the earlier error anymore, but get this one instead:
` Traceback (most recent call last):
  File "prepare_training_data.py", line 24, in <module>
    from bert.tokenization import FullTokenizer
ModuleNotFoundError: No module named 'bert.tokenization'`

Maybe this is unrelated to the earlier one and I should start a new issue?

I was also seeing if there are any updates to requirements.txt due to which I might be getting this error, but there doesn't seem to be a requirements.txt in the current version of the repo.

**Comment by vgtomahawk** [comment]
Thanks a lot! prepare_training_data.py runs fine now!
